language: python
sudo: false

python:
  - "2.7"
  - "3.3"
  - "3.4"

env:
  global:
    - INFERENCE=1
    - ZODB=1
    - INFERENCE=1 ZODB=1
    - secure: "maYggIWCt6+Oj+B/+XDP9VAPBr6h9iiUyeyQimbQDrqoiygmX9RI4fPlJfztNk+1iI4BHSXQjXziOd/6iAUhAt6PLUNaR7UxLPNhiDXkmQlrMsIAVXOIhPSlZLpMs0MbYQT6UFAR3ZE+kIObNtj4eqNjBs6uVAmeA103Xa0XR4A="
    - secure: "MzPh6i5mG7huxFspgu3us2d32+bRYwQRD34u0pcP2WvElsHkbAz/Y+5Gw3PEaP8U8UWdnFBeOM/siyJRMxFMSAIbweyGCwJzW0XpdiWNK0yU1bMbrCSRb8p+rlYECoNCEK3NgfY689A4z8bhE6c6xmwFtEND3XAVhw7qiktPNbg="

matrix:
  include:
    - python: "3.4"
      env:
        - DEPLOY=1
        - secure: "e/CvkQbT0zxsqKBYJNbIymw1XOvwF3Go4BjkUJNJpW9F3keEQvYHyOc6dZGArt9YSBTkmnHb1uvHhA3x2j+cz4wdTH3QdHWMCRJ79tUhALuBQiOgDQsUuEG16GrgseQrIQrxMgAFK/tOQUJwqdnpdZxK3u9lfdcPcImYJ3Dv4Uw="

install: ./.travis.sh

script:  
  - py.test tests

after_success:
  - ./codespeed-submit.sh
  - ./travis-downstream-trigger.sh
  - ./deploy.sh
