language: python

python:
  - "2.7"
  - "3.2"
  - "3.4"

env:
  - INFERENCE=1
  - ZODB=1
  - INFERENCE=1 ZODB=1

install:
  - "pip install -r requirements.txt"
  - "if [[ $INFERENCE ]] ; then"
  - "   pip install -r inference.requirements.txt"
  - "fi"
  - "if [[ $ZODB ]] ; then"
  - "   pip install -r zodb.requirements.txt"
  - "fi"

script:  
  - python tests/test.py
