language: python
sudo: required
python:
- '2.7'
- '3.4'
- '3.6'
- '3.7'
env:
  global:
  - INFERENCE=1
  - ZODB=1
  - INFERENCE=1 ZODB=1
  - secure: maYggIWCt6+Oj+B/+XDP9VAPBr6h9iiUyeyQimbQDrqoiygmX9RI4fPlJfztNk+1iI4BHSXQjXziOd/6iAUhAt6PLUNaR7UxLPNhiDXkmQlrMsIAVXOIhPSlZLpMs0MbYQT6UFAR3ZE+kIObNtj4eqNjBs6uVAmeA103Xa0XR4A=
  - secure: MzPh6i5mG7huxFspgu3us2d32+bRYwQRD34u0pcP2WvElsHkbAz/Y+5Gw3PEaP8U8UWdnFBeOM/siyJRMxFMSAIbweyGCwJzW0XpdiWNK0yU1bMbrCSRb8p+rlYECoNCEK3NgfY689A4z8bhE6c6xmwFtEND3XAVhw7qiktPNbg=
  - secure: cfS4PrZryBvvXT/lCm0sCiPMcErH7xyulZ6OSucIDP9P+tVJysaImZ0o+/IyVRO/Uum7ZpS8iS+GNhHIq0vtbc5nlHT6JVJyuvxWwdYQgaNwKmByd2wycL45tF8cVDTArhvVUkz/6BQ0qIxoRyDxRI8d2UqrsOVGgAX5ZF64RkI=
  - secure: MFitOXqnbcs4nB0+A8TfLu1nMTCyOmoJQYlp24MOm3tNrCe64KZNxk8/FhhR5CJRBbzY8enbyg0yov6g1jkHDPCDEVRlm3VM4ZcvLlOh428DPe5+E5tJ+onlxNrnEsBKDvKRTIocpk/Rd2rJc2GfQZr8m/qYBbZ3X/zfxao2+n8=
matrix:
  include:
  - python: '3.4'
    env:
    - DEPLOY=1
install: "./.travis.sh"
script:
- if [ ! "$DEPLOY" ] ; then py.test tests ; fi

after_success:
- ./.travis.success.sh
