language: python

python:
  - "2.7"
  - "3.2"
  - "3.4"

install:
  - "pip install -r requirements.txt"

matirx:
    - install: 
      - "pip install -r inference.requirements.txt"
      - "pip install -r zodb.requirements.txt"
    - install: 
      - "pip install -r zodb.requirements.txt"
    - install: 
      - "pip install -r inference.requirements.txt"

script:  
  - python tests/test.py
